- name: Copy service pod yaml
  copy:
    src: "{{ servideo_config_dir }}la_saillante/wordpress/pod/lasaillante_pod.yaml"
    dest: "~/{{ service_pod_yaml }}"
  become: true
  become_user: "{{ service_user }}"

- name: ensure Database directory exists
  file:
    path: "~/database"
    state: directory
    mode: '0770'
  become: true
  become_user: "{{ service_user }}"

- name: Ensure Wordpress data directory exists
  file:
    path: "~/wp_data"
    state: directory
    mode: '0770'
  become: true
  become_user: "{{ service_user }}"

- name: Ensure Apache data directory exists
  file:
    path: "~/apache_data"
    state: directory
    mode: '0770'
  become: true
  become_user: "{{ service_user }}"

- name: Ensure PHP data directory exists
  file:
    path: "~/php_data"
    state: directory
    mode: '0770'
  become: true
  become_user: "{{ service_user }}"

- name: Register "{{ service_systemd_name }}" systemd unit
  vars:
    container_run_as_user: "{{ service_user }}"
    container_run_as_group: "{{ service_user }}"
    container_image_list: "{{ service_container_image_names }}"
    container_name: "{{ service_systemd_name }}"
    container_pod_yaml: "{{ service_pod_yaml }}"
    container_state: running
  import_role:
    name: ikke_t.podman_container_systemd

- name: Ensure the service is started
  become: true
  become_user: "{{ service_user }}"
  systemd:
   name: "{{ service_systemd_name }}-container-pod-{{ service_user }}.service" 
   scope: user
   state: started

