FROM registry.access.redhat.com/ubi8/ubi-minimal
USER root
RUN microdnf install haproxy; microdnf clean all; systemctl enable haproxy;
LABEL maintainer="Romain Chantereau"

EXPOSE {% for item in port_mapping %}{{ item.exposed_port }}/{{ item.protocol }} {% endfor %}

# Start the service
CMD [ "/sbin/init" ]
