- name: Register Server
  redhat_subscription:
    state: present
    username: "{{ redhat_portal_username }}"
    password: "{{ redhat_portal_password }}"
    pool: "{{ redhat_rhel8_subscription_pool }}"
    syspurpose:
      usage: "Development/Test"
      #role: "Red Hat Enterprise Server"
      service_level_agreement: "Self-Support"
      #addons:
      #  - "Smart Management"
      sync: true
