- name: Configure IPSEC VPN as responder
  include_role:
    name: ansible-network.rhel
    tasks_from: cloud_vpn/configure_vpn_responder
  vars:
    cloud_vpn_name: ansibled_vpn
    cloud_vpn_psk: 1234567
    cloud_vpn_responder_provider: rhel
    cloud_vpn_responder_private_ip: hetzner001.servideo.org
    cloud_vpn_responder_tunnel_ip: 192.168.7.254
    cloud_vpn_responder_provider: rhel
    cloud_vpn_responder_public_ip: "@hetzner001.servideo.org"
    cloud_vpn_mode: main
    cloud_vpn_routing: static
    cloud_vpn_initiator_public_ip: "%any"
    cloud_vpn_responder_tunnel_interface_mark: "1/0xffffffff"
    cloud_vpn_responder_tunnel_interface: vti0


