- include_role:
    name: linux-system-roles.network 
  vars:
    network_connections:
      - name: "{{ connection_name }}"
        #persistent_state: present  # default
        type: ethernet
        autoconnect: yes
        interface_name: "{{ interface_name }}"
        ip:
          dhcp4: yes
          address: 95.217.96.40/29
          dns:
            - 46.182.19.48
            - 204.152.184.76
            - 2001:4f8:0:2::14
            - 194.150.168.168
            - 208.67.222.222
            - 208.67.220.220
            - 192.71.245.208
            - 51.15.98.97
            - 195.10.195.195
          dns_search: 
            - servideo.org

