- hosts: hetzners
  roles:
    - servideo.redhat.rhel8
    - servideo.redhat.insight
    - role: servideo.pinfra.extra_vg
      vars:
        vgname: vg.vm
        pv_devices:
          - /dev/sda3
          - /dev/sdb3
    - role: servideo.pinfra.extra_netif
      vars:
        connection_name: "Ethernet connexion"
        interface_name: enp0s31f6
