FROM registry.redhat.io/rhacm1-tech-preview/coredns-rhel8:v1.0.1-2
USER root
LABEL maintainer="Romain Chantereau"
# Copy config
COPY Corefile /Corefile
COPY db/* /
COPY keys/* /
# Start the service
EXPOSE {% for item in port_mapping %}{{ item.exposed_port }}/{{ item.protocol }} {% endfor %}

ENTRYPOINT ["/coredns"]
