- name: Build "{{ service_systemd_name }}" container image
  containers.podman.podman_image:
          name: "{{ item }}"
          path: "{{ build_basedir }}{{ builddir }}/{{ item }}"
          force: true
          username: "{{ redhat_portal_username }}"
          password: "{{ redhat_portal_password }}"
          build:
            annotation:
             app: "{{ service_systemd_name }}"
  loop: "{{ service_container_image_names_to_build }}"

