---
# tasks file for haproxy reverse proxy

- name: init the build & running env
  import_role:
    name: servideo.pod.service

# Need to kill all processes (like podman)
- name: Clean after removal
  block:
  - name: del user
    import_tasks: del_user.yml
    become: true
  when: service_state == "absent"
