- name: Create the build directory if it does not exist
  file:
    path: "{{ build_basedir }}/{{ builddir }}"
    state: directory
- name: Copy the Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ build_basedir }}/{{ builddir }}/Dockerfile"
- name: Copy the configuration
  copy:
    src: "{{ servideo_config_dir }}reverse_http_proxy/haproxy.cfg"
    dest: "{{ build_basedir }}/{{ builddir }}"

