- name: Add ”{{ service_name }}” system account
  user:
    name: "{{ service_user }}"
    comment: "{{ service_systemd_name }} system account"
    system: yes
    state: present
- name: Check "{{ service_systemd_name }}" subid
  import_role:
    name: ikke_t.podman_container_systemd
    tasks_from: check_subid
  vars:
    container_run_as_group: "{{ service_user }}"
    container_run_as_user: "{{ service_user }}"

