---
# tasks file for dns
- name: Prepare the build directory
  import_tasks: prepare_build.yml
- name: Build container image
  import_tasks: build.yml
- name: Clean the build directory
  import_tasks: clean_builddir.yml
