- name: Enable service port {{ service_name }}
  firewalld:
    service: dns
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
- name: Check socat is installed
  package:
    name: socat
    state: present
- name: Deploy the socat proxy/proxies to {{ service_name }}
  template:
    src: systemd-service-proxy-socat.j2
    dest: "{{ service_files_dir }}/proxy-to-{{ service_name }}-port-{{ item.ext_port }}.service"
    owner: root
    group: root
  loop: "{{ port_mapping }}"
  when: item.protocol == "udp"
  register: service_file
- name: Ensure socat proxy to {{ service_name }} is enabled at boot
  systemd:
    name: "proxy-to-{{ service_name }}-port-{{ item.ext_port }}"
    enabled: yes
    daemon_reload: yes
  loop: "{{ port_mapping }}"
  when: item.protocol == "udp"
- name: Ensure socat proxy to {{ service_name }} is started
  systemd:
    name: "proxy-to-{{ service_name }}-port-{{ item.ext_port }}"
    state: started
  loop: "{{ port_mapping }}"
  when: item.protocol == "udp"

- name: Setup systemd stream socket(s) for proxyd for {{ service_name }}
  template:
    src: systemd-socket-proxyd.j2
    dest: "{{ service_files_dir }}/proxyd-to-{{ service_name }}-{{ item.protocol }}-port-{{ item.ext_port }}.socket"
    owner: root
    group: root
  register: socket_file
  loop: "{{ port_mapping }}"
  when: item.protocol == "tcp"
- name: Setup systemd stream service(s) for proxyd for {{ service_name }}
  template:
    src: systemd-service-proxyd.j2
    dest: "{{ service_files_dir }}/proxyd-to-{{ service_name }}-{{ item.protocol }}-port-{{ item.ext_port }}.service"
    owner: root
    group: root
  register: service_file
  loop: "{{ port_mapping }}"
  when: item.protocol == "tcp"
- name: Ensure proxyd socket to {{ service_name }} is enabled at boot
  systemd:
    name: "proxyd-to-{{ service_name }}-{{ item.protocol }}-port-{{ item.ext_port }}.socket"
    enabled: yes
    daemon_reload: yes
  loop: "{{ port_mapping }}"
  when: item.protocol == "tcp"
- name: Ensure proxyd socket to {{ service_name }} is started
  systemd:
    name: "proxyd-to-{{ service_name }}-{{ item.protocol }}-port-{{ item.ext_port }}.socket"
    state: started
  loop: "{{ port_mapping }}"
  when: item.protocol == "tcp"


