---
# vars file for dns
service_user: "coredns"
service_systemd_name: "CoreDNS"
service_container_image_names:
  - "coredns"
port_mapping:
  - exposed_port: "53"
    host_port: "1053"
    ext_port: "53"
    protocol: "udp"
  - exposed_port: "53"
    host_port: "1053"
    ext_port: "53"
    protocol: "tcp"

