---
# vars file for wordpress pod
service_user: "lasaillante"
service_systemd_name: "La-saillante-wordpress"
service_pod_yaml: "la_saillante_pod.yaml"
service_container_image_names:
  - "bitnami/mariadb:10.5.10"
  - "bitnami/wordpress:5.7.2"

